name: Build & Deploy Frontend to GCS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # Optional: set backend URL for the build if you need it
          VITE_API_URL: ${{ secrets.FRONTEND_BACKEND_URL }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
        run: npm run build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK components
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: proto-475415
          export_default_credentials: true

      - name: Upload build to GCS (sync)
        env:
          BUCKET: proto-475415-frontend
        run: |
          gsutil -m rsync -r dist/ "gs://${BUCKET}/"
          # Make objects public (quick method)
          gsutil -m acl set -R -a public-read "gs://${BUCKET}"
          # configure GCS static site
          gsutil web set -m index.html -e 404.html "gs://${BUCKET}"
          echo "https://storage.googleapis.com/${BUCKET}/index.html"
